repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: metrics-server
    namespace: monitoring
    chart: bitnami/metrics-server
    version: 5.5.2
    values:
      - args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP
        resources:
          limits:
            cpu: 40m
            memory: 100Mi
          requests:
            cpu: 40m
            memory: 100Mi
