apiVersion: v1
kind: ConfigMap
metadata:
  name: doesNotMatter  # can be anything
data:
  fluent-bit-service.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Plugins_File plugins.conf

  fluent-bit-output.conf: |
    [OUTPUT]
        Name  logzio
        Match *
        logzio_token token-goes-here
        logzio_url   https://listener.logz.io:8071
